# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/anghosh/Data/Workspace/UE5 Projects/FunWithCubes/FunWithCubes.uproject

TARGETS = \
	FunWithCubes-Linux-DebugGame  \
	FunWithCubes-Linux-Shipping  \
	FunWithCubes \
	FunWithCubesEditor-Linux-DebugGame  \
	FunWithCubesEditor-Linux-Shipping  \
	FunWithCubesEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend FunWithCubesEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug FunWithCubesEditor-Linux-Debug


FunWithCubes-Linux-DebugGame:
	 $(PROJECTBUILD) FunWithCubes Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

FunWithCubes-Linux-Shipping:
	 $(PROJECTBUILD) FunWithCubes Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

FunWithCubes:
	 $(PROJECTBUILD) FunWithCubes Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

FunWithCubesEditor-Linux-DebugGame:
	 $(PROJECTBUILD) FunWithCubesEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

FunWithCubesEditor-Linux-Shipping:
	 $(PROJECTBUILD) FunWithCubesEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

FunWithCubesEditor:
	 $(PROJECTBUILD) FunWithCubesEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
